package org.scalacheck

import cats.*
import cats.effect.IO
import cats.effect.testkit.TestControl
import cats.effect.unsafe.IORuntime
import cats.effect.unsafe.implicits.*
import cats.syntax.all.*
import org.scalacheck.Prop.{forAll, propBoolean, undecided}
import org.scalacheck.gen.Unsafe.promote
import org.scalacheck.util.Pretty

/** A monadic property API for [[https://scalacheck.org ScalaCheck]] — the ability to interleave
  * effectful `M[_]` computations (typically `cats.effect.IO`) with property generation and
  * assertions, driving them to a `Prop`.
  *
  * This is a Scala 3 / Cats port of Haskell QuickCheck's `Test.QuickCheck.Monadic`
  * ([[https://hackage.haskell.org/package/QuickCheck/docs/Test-QuickCheck-Monadic.html]]): `run`,
  * `pick`, `pre`, `wp`, `assert`, `stop`, `monitor`, `forAllM`, and the `monadic*` runners. It
  * lives in the `org.scalacheck` package because it builds on ScalaCheck internals (`Gen.gen`,
  * `Gen.R#doApply/retrieve/withLabels`, `gen.Unsafe.promote`, `Prop.startSeed`).
  *
  * See NOTICE for attribution to QuickCheck (ported-from) and ScalaCheck (built-on).
  */
// TODO: Assertions have color codes and emoji for visibility on color-capable terminals.
// These should be configurable (i.e., disabled) to make logs easier to parse
object PropertyM:
    /** Like 'assert' but allows caller to specify an explicit message to show on failure.
      */
    def assertWith[M[_]](condition: Boolean, msg: String)(using
        monadM: Monad[M]
    ): PropertyM[M, Unit] = {
        val prefix =
            if condition
            then Console.GREEN + "\t✅  " + Console.RESET
            else Console.RED + "\t❌ " + Console.RESET
        for {
            _ <- monitor(prop => (prefix ++ msg) |: prop)
            _ <- assert(condition)
        } yield ()
    }

    /** Allows embedding non-monadic properties into monadic ones.
      */
    def assert[M[_]](bool: Boolean)(using Monad[M]): PropertyM[M, Unit] = {
        if bool then monadForPropM.pure(())
        else fail_(Console.RED ++ "Assertion(s) FAILED" ++ Console.RESET)
    }

    /** Short-circuit execution and fail with the given message.
      */
    def fail_[M[_], A](s: String)(using monadM: Monad[M]): PropertyM[M, A] =
        stop(s |: false)

    // FIXME: Error messages appear to be reported in reverse chronological order?

    /** Stop execution by short-circuiting and exiting with this prop
      */
    def stop[M[_], P, A](prop: P)(using toProp: P => Prop, monadM: Monad[M]): PropertyM[M, A] =
        PropertyM(_ => Gen.const(monadM.pure(toProp(prop))))

    // NOTE (from the quickcheck version): should think about strictness/exceptions here

    /** Allows making observations about the test data
      */
    def monitor[M[_]](f: Prop => Prop)(using monadM: Monad[M]): PropertyM[M, Unit] =
        PropertyM(k => k(()).map((m: M[Prop]) => m.map(f)))

    // -- should be called lift?

    /** Tests preconditions. Unlike 'assert' this does not cause the property to fail, rather it
      * discards them just like using the implication combinator 'Test.QuickCheck.Property.==>'.
      *
      * This allows representing the <https://en.wikipedia.org/wiki/Hoare_logic Hoare triple>
      *
      * > {p} x ← e{q}
      *
      * as `` pre p x <- run e assert q ``
      */
    def pre[M[_]](condition: Boolean)(using Monad[M]): PropertyM[M, Unit] =
        if condition then monadForPropM.pure(()) else stop(undecided)

    /** The <https://en.wikipedia.org/wiki/Predicate_transformer_semantics#Weakest_preconditions
      * weakest precondition> > wp(x ← e, p) can be expressed as in code as `wp(e, (x => p))`.
      */
    def wp[M[_], A, B](m: M[A], k: A => PropertyM[M, B])(using monadM: Monad[M]): PropertyM[M, B] =
        run(m) >>= k

    /** | The lifting operation of the property monad. Allows embedding monadic 'IO'-actions in properties.
      */
    def run[M[_], A](m: M[A])(using monadM: Monad[M]): PropertyM[M, A] =
        PropertyM(x => promote(x).map(k => m >>= k))

    /** Quantification in monadic properties to 'pick', with a notation similar to 'forAll'. Note:
      * values generated by 'forAllM' do not shrink.
      */
    def forAllM[M[_], A, B](gen: Gen[A], k: A => PropertyM[M, B])(using
        monadM: Monad[M],
        pp: A => Pretty
    ): PropertyM[M, B] =
        pick(gen) >>= k

    /** Quantification in a monadic property, fits better with /do-notation/ than 'forAllM'. Note:
      * values generated by 'pick' do not shrink.
      */
    def pick[M[_], A](
        generator: Gen[A]
    )(using monadM: Monad[M], pp: A => Pretty): PropertyM[M, A] = {
        // Create a new continuation...
        PropertyM(k =>
            // that returns a new generator...
            Gen.gen((p0, s0) =>
                // evaluate our "wrapped" `generator` at the same parameter and seed...
                val ra = generator.doApply(p0, s0)
                // then construct a new Gen.R[M[Prop]] by flat mapping through at the next seed and applying the labels
                val rmp = ra.flatMap(a => k(a).doApply(p0, ra.seed)).withLabels(ra.labels)

                // If either of the generator evaluations is empty, then return Gen.R with a "None" result.
                // This could happen, for instance, due to a "suchThat" applied to the generator
                if ra.retrieve.isEmpty || rmp.retrieve.isEmpty
                then Gen.r(r = None, sd = rmp.seed).withLabels(rmp.labels)
                else {
                    val res = for {
                        p <- rmp.retrieve.get
                    } yield {
                        // A Gen.R has a _set_ of labels, but a Prop.Result carries a list of Prop.Arg, and Prop.Arg
                        // only allow for a single label per argument.
                        // forAllNoShrink uses :  val labels = gr.labels.mkString(","), so that's what we'll use too
                        val label = rmp.labels.mkString(",")
                        forAll(Gen.const(ra.retrieve.get).label(label))(_ => p)
                    }
                    Gen.r(r = Some(res), sd = rmp.seed).withLabels(rmp.labels)
                }
            )
        )
    }

    /** Bracket a [[cats.effect.Resource]] around a [[PropertyM]] body. Acquires the resource inside
      * [[cats.effect.IO.uncancelable]], polls the body so it remains cancelable, and guarantees
      * release on success, failure, or cancellation — matching `Resource.use` semantics.
      */
    def useResource[R, A](r: cats.effect.Resource[cats.effect.IO, R])(
        body: R => PropertyM[cats.effect.IO, A]
    )(using @scala.annotation.unused toProp: A => Prop): PropertyM[cats.effect.IO, A] = PropertyM {
        k =>
            Gen.gen { (p, s) =>
                val io: cats.effect.IO[Prop] = cats.effect.IO.uncancelable { poll =>
                    r.allocated.flatMap { case (env, release) =>
                        body(env).unPropertyM(k).doApply(p, s).retrieve match {
                            case Some(bodyIo) => poll(bodyIo).guarantee(release)
                            case None         => release.as(Prop.undecided)
                        }
                    }
                }
                Gen.r(Some(io), s.next)
            }
    }

    // ===================================
    // run functions
    // ===================================

    // TODO: Better docs, this is an  experiment so far
    /** Run an IO action within a TestControl
      * @param prop
      * @param testControlCallback
      * @param toProp
      * @tparam A
      * @return
      */
    def monadicTestControlExecute[A](
        prop: => PropertyM[IO, A],
        testControlCallback: TestControl[Prop] => IO[Prop]
    )(using toProp: A => Prop): Prop =
        monadic(
          runner = (ioProp: IO[Prop]) =>
              (for {
                  tc <- TestControl.execute(ioProp.map(Prop.secure(_)))
                  prop <- testControlCallback(tc)
              } yield prop).unsafeRunSync(),
          m = prop
        )

    /** Run the property using `TestControl.executeEmbed` */
    // TODO: executeEmbed also takes a seed that governs the random execute of fibers.
    // We should figure out how to pass the seed to/from scalacheck
    def monadicTestControlExecuteEmbed[A](
        prop: => PropertyM[IO, A]
    )(using toProp: A => Prop): Prop =
        monadic(
          runner = (ioProp: IO[Prop]) =>
              TestControl.executeEmbed(ioProp.map(Prop.secure(_))).unsafeRunSync(),
          m = prop
        )

    /** Runs the property monad for 'IO'-computations. * */
    // NOTE: the by-name parameter is necessary, otherwise exceptions won't be caught properly. See the
    // "exception" demo.
    def monadicIO[A](
        prop: => PropertyM[IO, A]
    )(using toProp: A => Prop, ioRuntime: IORuntime): Prop =
        // NOTE: I'm pretty sure this is what we want -- Prop.secure evaluates its argument only at the time
        // it is actually referenced, so we should be catching the exception here
        monadic(runner = (ioProp: IO[Prop]) => ioProp.map(Prop.secure(_)).unsafeRunSync(), m = prop)

    /** Given an arbitrary monadic runner and a PropertyM, return a Prop */
    def monadic[M[_], A](runner: M[Prop] => Prop, m: => PropertyM[M, A])(using
        toProp: A => Prop,
        monadM: Monad[M]
    ): Prop = {
        // This is adapted from the haskell equivalent:
        //        instance Testable prop => Testable (Gen prop) where
        //          property mp = MkProperty $ do p <- mp; unProperty (property p)
        // but I'm not totally sure it's correct. Do I need to slide the seed here?
        val testableGenProp: (Gen[Prop] => Prop) = mp =>
            Prop.apply(f = params => {
                val (p, s) = Prop.startSeed(params)
                mp.pureApply(p, s).apply(p)
            })
        Prop.secure(testableGenProp(monadic1(m).map(runner)))
    }
    /*

    monadic :: (Testable a, Monad m) => (m Property -> Property) -> PropertyM m a -> Property
    monadic runner m = property (fmap runner (monadic' m))

     */

    def monadic1[M[_], A](
        m: => PropertyM[M, A]
    )(using toProp: A => Prop, monadM: Monad[M]): Gen[M[Prop]] =
        m.unPropertyM(prop => monadM.pure(toProp(prop)))

    // ===================================
    // Type class stuff
    // ===================================

    // What is the correct way to make these instances available? just as implicit defs?

    implicit def functorForPropM[M[_]]: Functor[[A] =>> PropertyM[M, A]] =
        new Functor[[A] =>> PropertyM[M, A]] {
            override def map[A, B](fa: PropertyM[M, A])(f: A => B): PropertyM[M, B] = fa.map(f)
        }

    implicit def applicativeForPropM[M[_]](using Monad[M]): Applicative[[A] =>> PropertyM[M, A]] =
        new Applicative[[A] =>> PropertyM[M, A]] {
            override def pure[A](x: A): PropertyM[M, A] = PropertyM(k => k(x))

            override def ap[A, B](mf: PropertyM[M, A => B])(mx: PropertyM[M, A]): PropertyM[M, B] =
                mf.bind(f => mx.bind(x => pure(f(x))))
        }

    implicit def monadForPropM[M[_]](using Monad[M]): Monad[[A] =>> PropertyM[M, A]] =
        new Monad[[A] =>> PropertyM[M, A]] {
            override def pure[A](x: A): PropertyM[M, A] = PropertyM(k => k(x))

            override def flatMap[A, B](fa: PropertyM[M, A])(
                f: A => PropertyM[M, B]
            ): PropertyM[M, B] = fa.bind(f)

            // Not stack-safe: `PropertyM` is a CPS layer over `Gen`, which has no trampoline to
            // hook into, and property bodies are shallow (a handful of `pick`/`run`/`assert`
            // steps), not deep monadic recursion. A straightforward unfold via `bind` is correct
            // for that usage and keeps `iterateWhileM`/`whileM`/etc. from hitting `???`.
            override def tailRecM[A, B](a: A)(f: A => PropertyM[M, Either[A, B]]): PropertyM[M, B] =
                f(a).bind {
                    case Left(a2) => tailRecM(a2)(f)
                    case Right(b) => pure(b)
                }
        }

/** The property monad is really a monad transformer that can contain
  * monadic computations in the monad @m@ it is parameterized by:
  *
  * @m@ - the @m@-computations that may be performed within @PropertyM@
  *
  *     Elements of @PropertyM m a@ may mix property operations and @m@-computations.
  */
case class PropertyM[M[_], A](unPropertyM: (A => Gen[M[Prop]]) => Gen[M[Prop]])(using
    monad: Monad[M]
) {
    def bind[B](f: A => PropertyM[M, B]): PropertyM[M, B] =
        PropertyM(k => this.unPropertyM(a => f(a).unPropertyM(k)))

    def map[B](f: A => B): PropertyM[M, B] =
        PropertyM(unPropertyM = (k: B => Gen[M[Prop]]) => this.unPropertyM((a: A) => k(f(a))))

}

// ===================================
// From here on out, its other haskell stuff that we don't currently need. I'm keeping it around for now because
// I've only barely glanced at it; maybe there's some other stuff in scalacheck/cats that corresponds to this
// and might be useful
// ===================================

//#ifndef NO_MONADFAIL
//instance Monad m => Fail.MonadFail (PropertyM m) where
//  fail = fail_
//#endif
//
//#ifndef NO_TRANSFORMERS
//instance MonadTrans PropertyM where
//  lift = run
//
//instance MonadIO m => MonadIO (PropertyM m) where
//  liftIO = run . liftIO
//#endif

//#ifndef NO_ST_MONAD
//-- | Runs the property monad for 'ST'-computations.
//--
//-- @
//-- -- Your mutable sorting algorithm here
//-- sortST :: Ord a => [a] -> 'Control.Monad.ST.ST' s (MVector s a)
//-- sortST = 'Data.Vector.thaw' . 'Data.Vector.fromList' . 'Data.List.sort'
//--
//-- prop_sortST xs = monadicST $ do
//--   sorted  \<- run ('Data.Vector.freeze' =<< sortST xs)
//--   assert ('Data.Vector.toList' sorted == sort xs)
//-- @
//--
//-- >>> quickCheck prop_sortST
//-- +++ OK, passed 100 tests.
//--
//monadicST :: Testable a => (forall s. PropertyM (ST s) a) -> Property
//monadicST m = property (runSTGen (monadic' m))
//
//runSTGen :: (forall s. Gen (ST s a)) -> Gen a
//runSTGen f = do
//  Capture eval <- capture
//  return (runST (eval f))
//#endif
//
//-- Exceptions
//
//
//#ifndef NO_EXCEPTIONS
//
//-- | Evaluate the value to Weak Head Normal Form (WHNF) and fail if it does not result in
//-- an expected exception being thrown.
//assertException ::
//     E.Exception exc
//  => (exc -> Bool) -- ^ Return `True` if that is the exception that was expected
//  -> a -- ^ Value that should result in an exception, when evaluated to WHNF
//  -> Property
//assertException isExc value = assertExceptionIO isExc (return value)
//
//
//-- | Make sure that a specific exception is thrown during an IO action. The result is
//-- evaluated to WHNF.
//assertExceptionIO ::
//     E.Exception exc
//  => (exc -> Bool) -- ^ Return `True` if that is the exception that was expected
//  -> IO a -- ^ An action that should throw the expected exception
//  -> Property
//assertExceptionIO isExc action =
//  monadicIO $ do
//    hasFailed <-
//      run
//        (E.catch
//           (do res <- action
//               res `seq` return False)
//           (return . isExc))
//    assert hasFailed
//
//#ifndef NO_DEEPSEQ
//
//-- | Same as `assertException`, but evaluate the value to Normal Form (NF) and fail if it
//-- does not result in an expected exception being thrown.
//assertDeepException ::
//     (NFData a, E.Exception exc)
//  => (exc -> Bool) -- ^ Return True if that is the exception that was expected
//  -> a -- ^ Value that should result in an exception, when fully evaluated to NF
//  -> Property
//assertDeepException isExc value = assertException isExc (rnf value)
//
//-- | Make sure that a specific exception is thrown during an IO action. The result is
//-- evaluated to NF.
//assertDeepExceptionIO ::
//     (NFData a, E.Exception exc)
//  => (exc -> Bool) -- ^ Return True if that is the exception that was expected
//  -> IO a -- ^ An action that should throw the expected exception
//  -> Property
//assertDeepExceptionIO isExc action = assertExceptionIO isExc (fmap rnf action)
//
//#endif
//#endif
//
