package org.scalacheck

import cats.*
import cats.effect.{IO, MonadCancelThrow}
import cats.effect.syntax.all.*
import cats.effect.testkit.TestControl
import cats.effect.unsafe.IORuntime
import cats.effect.unsafe.implicits.*
import cats.syntax.all.*
import org.scalacheck.Prop.{forAll, propBoolean, undecided}
import org.scalacheck.gen.Unsafe.promote
import org.scalacheck.util.Pretty

/** A monadic property API for [[https://scalacheck.org ScalaCheck]] — the ability to interleave
  * effectful `M[_]` computations (typically `cats.effect.IO`) with property generation and
  * assertions, driving them to a `Prop`.
  *
  * This is a Scala 3 / Cats port of Haskell QuickCheck's `Test.QuickCheck.Monadic`
  * ([[https://hackage.haskell.org/package/QuickCheck/docs/Test-QuickCheck-Monadic.html]]): `run`,
  * `pick`, `pre`, `wp`, `assert`, `stop`, `monitor`, `forAllM`, and the `monadic*` runners. It
  * lives in the `org.scalacheck` package because it builds on ScalaCheck internals (`Gen.gen`,
  * `Gen.R#doApply/retrieve/withLabels`, `gen.Unsafe.promote`, `Prop.startSeed`).
  *
  * See NOTICE for attribution to QuickCheck (ported-from) and ScalaCheck (built-on).
  */
// TODO: Assertions have color codes and emoji for visibility on color-capable terminals.
// These should be configurable (i.e., disabled) to make logs easier to parse
object PropertyM:
    /** Like 'assert' but allows caller to specify an explicit message to show on failure.
      */
    def assertWith[M[_]](condition: Boolean, msg: String)(using
        monadM: Monad[M]
    ): PropertyM[M, Unit] = {
        val prefix =
            if condition
            then Console.GREEN + "\t✅  " + Console.RESET
            else Console.RED + "\t❌ " + Console.RESET
        for {
            _ <- monitor(prop => (prefix ++ msg) |: prop)
            _ <- assert(condition)
        } yield ()
    }

    /** Allows embedding non-monadic properties into monadic ones.
      */
    def assert[M[_]](bool: Boolean)(using Monad[M]): PropertyM[M, Unit] = {
        if bool then monadForPropM.pure(())
        else fail_(Console.RED ++ "Assertion(s) FAILED" ++ Console.RESET)
    }

    /** Short-circuit execution and fail with the given message.
      */
    def fail_[M[_], A](s: String)(using monadM: Monad[M]): PropertyM[M, A] =
        stop(s |: false)

    // `monitor`-based messages (`assertWith`, `stop`) come out innermost-first, i.e. reversed:
    // `monitor` decorates the *continuation*, so the outermost wrapper is applied last, and
    // `Prop.Result.label` accumulates into a `Set[String]` that `Pretty` renders with `mkString`.
    // Up to four labels that is insertion order and reads as reverse-chronological; from five on
    // the set becomes a `HashSet` and the order is arbitrary. `Result.args` is the only ordered
    // channel (a `List`), which is what `pick` already uses.

    /** Stop execution by short-circuiting and exiting with this prop
      */
    def stop[M[_], P, A](prop: P)(using toProp: P => Prop, monadM: Monad[M]): PropertyM[M, A] =
        PropertyM(_ => Gen.const(monadM.pure(toProp(prop))))

    // NOTE (from the quickcheck version): should think about strictness/exceptions here

    /** Allows making observations about the test data
      */
    def monitor[M[_]](f: Prop => Prop)(using monadM: Monad[M]): PropertyM[M, Unit] =
        PropertyM(k => k(()).map((m: M[Prop]) => m.map(f)))

    /** Tests preconditions. Unlike 'assert' this does not cause the property to fail, rather it
      * discards them just like using the implication combinator 'Test.QuickCheck.Property.==>'.
      *
      * This allows representing the <https://en.wikipedia.org/wiki/Hoare_logic Hoare triple>
      *
      * > {p} x ← e{q}
      *
      * as `` pre p x <- run e assert q ``
      */
    def pre[M[_]](condition: Boolean)(using Monad[M]): PropertyM[M, Unit] =
        if condition then monadForPropM.pure(()) else stop(undecided)

    /** The <https://en.wikipedia.org/wiki/Predicate_transformer_semantics#Weakest_preconditions
      * weakest precondition> > wp(x ← e, p) can be expressed as in code as `wp(e, (x => p))`.
      */
    def wp[M[_], A, B](m: M[A], k: A => PropertyM[M, B])(using monadM: Monad[M]): PropertyM[M, B] =
        run(m) >>= k

    /** | The lifting operation of the property monad. Allows embedding monadic 'IO'-actions in properties.
      */
    def run[M[_], A](m: M[A])(using monadM: Monad[M]): PropertyM[M, A] =
        PropertyM(x => promote(x).map(k => m >>= k))

    /** Quantification in monadic properties to 'pick', with a notation similar to 'forAll'. Note:
      * values generated by 'forAllM' do not shrink.
      */
    def forAllM[M[_], A, B](gen: Gen[A], k: A => PropertyM[M, B])(using
        monadM: Monad[M],
        pp: A => Pretty
    ): PropertyM[M, B] =
        pick(gen) >>= k

    /** Quantification in a monadic property, fits better with /do-notation/ than 'forAllM'. Note:
      * values generated by 'pick' do not shrink.
      */
    def pick[M[_], A](
        generator: Gen[A]
    )(using monadM: Monad[M], pp: A => Pretty): PropertyM[M, A] = {
        // Create a new continuation...
        PropertyM(k =>
            // that returns a new generator...
            Gen.gen((p0, s0) =>
                // evaluate our "wrapped" `generator` at the same parameter and seed...
                val ra = generator.doApply(p0, s0)
                // then construct a new Gen.R[M[Prop]] by flat mapping through at the next seed and applying the labels
                val rmp = ra.flatMap(a => k(a).doApply(p0, ra.seed)).withLabels(ra.labels)

                // If either of the generator evaluations is empty, then return Gen.R with a "None" result.
                // This could happen, for instance, due to a "suchThat" applied to the generator
                if ra.retrieve.isEmpty || rmp.retrieve.isEmpty
                then Gen.r(r = None, sd = rmp.seed).withLabels(rmp.labels)
                else {
                    val res = for {
                        p <- rmp.retrieve.get
                    } yield {
                        // A Gen.R has a _set_ of labels, but a Prop.Result carries a list of Prop.Arg, and Prop.Arg
                        // only allow for a single label per argument.
                        // forAllNoShrink uses :  val labels = gr.labels.mkString(","), so that's what we'll use too
                        val label = rmp.labels.mkString(",")
                        forAll(Gen.const(ra.retrieve.get).label(label))(_ => p)
                    }
                    Gen.r(r = Some(res), sd = rmp.seed).withLabels(rmp.labels)
                }
            )
        )
    }

    /** Bracket a [[cats.effect.Resource]] around a [[PropertyM]] body. Acquires the resource inside
      * [[MonadCancelThrow.uncancelable]], polls the body so it remains cancelable, and guarantees
      * release on success, failure, or cancellation — matching [[Resource.use]] semantics.
      */
    def useResource[M[_], R, A](r: cats.effect.Resource[M, R])(
        body: R => PropertyM[M, A]
    )(using F: MonadCancelThrow[M]): PropertyM[M, A] = PropertyM { k =>
        Gen.gen { (p, s) =>
            val m: M[Prop] = F.uncancelable { poll =>
                r.allocated.flatMap { case (env, release) =>
                    body(env).unPropertyM(k).doApply(p, s).retrieve match {
                        case Some(bodyM) => poll(bodyM).guarantee(release)
                        case None        => release.as(Prop.undecided)
                    }
                }
            }
            Gen.r(Some(m), s.next)
        }
    }

    // ===================================
    // run functions
    // ===================================

    // TODO: Better docs, this is an  experiment so far
    /** Run an IO action within a TestControl
      * @param prop
      * @param testControlCallback
      * @param toProp
      * @tparam A
      * @return
      */
    def monadicTestControlExecute[A](
        prop: => PropertyM[IO, A],
        testControlCallback: TestControl[Prop] => IO[Prop]
    )(using toProp: A => Prop): Prop =
        monadic(
          runner = (ioProp: IO[Prop]) =>
              (for {
                  tc <- TestControl.execute(ioProp.map(Prop.secure(_)))
                  prop <- testControlCallback(tc)
              } yield prop).unsafeRunSync(),
          m = prop
        )

    /** Run the property using `TestControl.executeEmbed` */
    // TODO: executeEmbed also takes a seed that governs the random execute of fibers.
    // We should figure out how to pass the seed to/from scalacheck
    def monadicTestControlExecuteEmbed[A](
        prop: => PropertyM[IO, A]
    )(using toProp: A => Prop): Prop =
        monadic(
          runner = (ioProp: IO[Prop]) =>
              TestControl.executeEmbed(ioProp.map(Prop.secure(_))).unsafeRunSync(),
          m = prop
        )

    /** Runs the property monad for 'IO'-computations. * */
    // NOTE: the by-name parameter is necessary, otherwise exceptions won't be caught properly. See the
    // "exception" demo.
    def monadicIO[A](
        prop: => PropertyM[IO, A]
    )(using toProp: A => Prop, ioRuntime: IORuntime): Prop =
        // NOTE: I'm pretty sure this is what we want -- Prop.secure evaluates its argument only at the time
        // it is actually referenced, so we should be catching the exception here
        monadic(runner = (ioProp: IO[Prop]) => ioProp.map(Prop.secure(_)).unsafeRunSync(), m = prop)

    /** Given an arbitrary monadic runner and a PropertyM, return a Prop */
    def monadic[M[_], A](runner: M[Prop] => Prop, m: => PropertyM[M, A])(using
        toProp: A => Prop,
        monadM: Monad[M]
    ): Prop = {
        // This is adapted from the haskell equivalent:
        //        instance Testable prop => Testable (Gen prop) where
        //          property mp = MkProperty $ do p <- mp; unProperty (property p)
        // but I'm not totally sure it's correct. Do I need to slide the seed here?
        val testableGenProp: (Gen[Prop] => Prop) = mp =>
            Prop.apply(f = params => {
                val (p, s) = Prop.startSeed(params)
                mp.pureApply(p, s).apply(p)
            })
        Prop.secure(testableGenProp(monadic1(m).map(runner)))
    }

    def monadic1[M[_], A](
        m: => PropertyM[M, A]
    )(using toProp: A => Prop, monadM: Monad[M]): Gen[M[Prop]] =
        m.unPropertyM(prop => monadM.pure(toProp(prop)))

    // ===================================
    // Type class stuff
    // ===================================

    given functorForPropM[M[_]]: Functor[[A] =>> PropertyM[M, A]] =
        new Functor[[A] =>> PropertyM[M, A]] {
            override def map[A, B](fa: PropertyM[M, A])(f: A => B): PropertyM[M, B] = fa.map(f)
        }

    given applicativeForPropM[M[_]]: Applicative[[A] =>> PropertyM[M, A]] =
        new Applicative[[A] =>> PropertyM[M, A]] {
            override def pure[A](x: A): PropertyM[M, A] = PropertyM(k => k(x))

            override def ap[A, B](mf: PropertyM[M, A => B])(mx: PropertyM[M, A]): PropertyM[M, B] =
                mf.flatMap(f => mx.flatMap(x => pure(f(x))))
        }

    given monadForPropM[M[_]]: Monad[[A] =>> PropertyM[M, A]] =
        new Monad[[A] =>> PropertyM[M, A]] {
            override def pure[A](x: A): PropertyM[M, A] = PropertyM(k => k(x))

            override def flatMap[A, B](fa: PropertyM[M, A])(
                f: A => PropertyM[M, B]
            ): PropertyM[M, B] = fa.flatMap(f)

            // Not stack-safe: `PropertyM` is a CPS layer over `Gen`, which has no trampoline to
            // hook into, so this overflows at ~1500 steps on a 1 MiB stack. Property bodies are
            // shallow (a handful of `pick`/`run`/`assert` steps), not deep monadic recursion, so a
            // straightforward unfold via `flatMap` is correct for that usage and keeps
            // `iterateWhileM`/`whileM`/etc. from hitting `???`.
            //
            // Rebuilding on `cats.data.ContT` does not help: `ContT.tailRecM` suspends its
            // recursion in `Defer[M]` and never calls `Monad[M].tailRecM`, so ScalaCheck's
            // stack-safe `Gen.tailRecM` is off the path — and a lawful `Defer[Gen]` is
            // unimplementable, since flattening nested defers needs a reifiable node (cf.
            // `Eval.Defer`) and `Gen` is sealed with only opaque `Gen.gen` available.
            override def tailRecM[A, B](a: A)(f: A => PropertyM[M, Either[A, B]]): PropertyM[M, B] =
                f(a).flatMap {
                    case Left(a2) => tailRecM(a2)(f)
                    case Right(b) => pure(b)
                }
        }

/** The property monad is really a monad transformer that can contain monadic computations in the
  * monad `M` it is parameterized by. Elements of `PropertyM[M, A]` may mix property operations and
  * `M`-computations.
  *
  * @tparam M
  *   the `M`-computations that may be performed within `PropertyM`
  * @tparam A
  *   the value this step produces — what the continuation is handed. The continuation itself always
  *   returns `Gen[M[Prop]]`.
  */
case class PropertyM[M[_], A](unPropertyM: (A => Gen[M[Prop]]) => Gen[M[Prop]]) {

    def flatMap[B](f: A => PropertyM[M, B]): PropertyM[M, B] =
        PropertyM(k => this.unPropertyM(a => f(a).unPropertyM(k)))

    def map[B](f: A => B): PropertyM[M, B] =
        PropertyM(unPropertyM = (k: B => Gen[M[Prop]]) => this.unPropertyM((a: A) => k(f(a))))
}
